name: Generate Snake

on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: hayfordafriyie
          outputs: dist/snake.svg

      - name: Upload snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg

      - name: Push generated SVG to the repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generated snake contribution grid"
          git push
